### ISSUE TITLE
Make repository dynamic

### ISSUE THREAD

**Issue by dm-pf** [The-3Labs-Team/nova-github-cards#4]
Hi, I just noticed this package and it looks very nice.

We currently manage github repositories in our Nova project and it could be a nice addition to add these cards to the details window of each project.

So I'd like to request having the option of vendor/repository be a dynamic property so we could display data of many different repositories.

Thanks!

**Comment by murdercode** [comment]
Hi, I'm glad you like the package!

Regarding your request, each card can accept customised parameters, for example:

```php
<?php
use \The3LabsTeam\NovaGithubCards\LatestCommitsTable;
...

(new LatestCommitsTable(
    name: 'The name of the card (string)', 
    vendor: 'The name of your vendor (string)', 
    repository: 'The name of your repo (string)', 
    branch: 'The name of your branch (string)', 
    perPage: 'Total of results (int)', 
    cache: 'The cache in seconds (int)')
 )
```

Please note that the name must always be different, otherwise the cache key (which in Nova's metrics are created using it) will be shared.

Is this solution suitable for you?
